### ISSUE TITLE
nice one!

### ISSUE THREAD

**Issue by mizrael** [aventius-software/BlazorGE#11]
hi @aventius-software ! Thanks for mentioning me in your readme, really appreciated :) Just FYI, I published a new library that helps deal with the HTML Canvas, maybe you can find it useful: https://github.com/mizrael/Blazorex
Cheers!

**Comment by aventius-software** [comment]
Hi @mizrael! you're welcome, I really liked your series on Blazor game development. I'll check out your HTML canvas lib :)

**Comment by aventius-software** [comment]
Closing... ;-)
