### ISSUE TITLE
Guide on how to run the demo

### ISSUE THREAD

**Issue by jscraftsman** [aventius-software/BlazorGE#6]
Can you provide a guide on how to run the demo?

**Comment by aventius-software** [comment]
Do you mean a guide on how to start it up from Visual Studio or how to play it? Or are you having a different issue?

**Comment by jscraftsman** [comment]
How to run on visual studio, I'm getting errors when trying to run it

**Comment by aventius-software** [comment]
There should be only these three steps

- First make sure you've got the latest version of Visual Studio 2022, you may get .NET errors if you have an older version
- Set the demo game project as the 'startup' project if its not already set
- Click the start with debugging button as per normal

Then it should start as any normal blazor webassembly project and you should see a black canvas element with some text saying 'press space' or something like that once the app boots. You may have to click on the browser window to set focus, seems to not autofocus when using Chrome but its fine in FireFox... If you're getting some other errors please could you specify the error(s) or screen shot them?

**Comment by jscraftsman** [comment]
It is working now, thanks!
![image](https://user-images.githubusercontent.com/1636276/223663780-83a635c7-5e83-47b3-90bc-fcc7345cdb9c.png)

Marking this as closed
